(function(g){var window=this;var Dsa=function(a,b){return g.Vb(a,b)},Y5=function(a,b,c){a.w.set(b,c)},Z5=function(a){Y5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},$5=function(a,b,c){g.Ia(c)||(c=[String(c)]);
g.gn(a.w,b,c)},Esa=function(a,b){var c=[];
g.mk(b,function(d){try{var e=g.Wn.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Vn(e)&&c.push(d)},a);
return c},Fsa=function(a,b){var c=Esa(a,b);
(0,g.z)(c,function(d){g.Wn.prototype.remove.call(this,d)},a)},Gsa=function(a,b){g.Za(a,b)||a.push(b)},a6=function(a){var b=0,c;
for(c in a)b++;return b},Hsa=function(a,b){var c=b instanceof g.zc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.Ac(c)},b6=function(){},Isa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Jsa=function(a){if(a.rd&&"function"==typeof a.rd)return a.rd();
if("string"===typeof a)return a.split("");if(g.Ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},Ksa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ja(a)||"string"===typeof a)(0,g.z)(a,b,void 0);else{if(a.le&&"function"==typeof a.le)var c=a.le();else if(a.rd&&"function"==typeof a.rd)c=void 0;else if(g.Ja(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=Jsa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Lsa=function(a,b,c,d){var e=new g.Vm(null,void 0);
a&&g.Wm(e,a);b&&g.Xm(e,b);c&&g.Ym(e,c);d&&(e.u=d);return e},c6=function(a,b){g.fp[a]=!0;
var c=g.dp();c&&c.publish.apply(c,arguments);g.fp[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Sm;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Msa(this,a.capabilities||""),Nsa(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},Msa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Oa(Dsa,Osa)).forEach(function(c){a.capabilities.add(c)})},Nsa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Psa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Qsa=function(a){return new e6(a)},Rsa=function(a){return g.Ia(a)?(0,g.Ic)(a,Qsa):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Ia(a)?"["+(0,g.Ic)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Ssa=function(a){return(0,g.Ic)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.Va(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.Va(a,function(c){return f6(c,b)})},l6=function(a){try{var b=(0,g.Fs)(),c=(0,g.Es)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Tsa=function(){var a=(0,g.Es)();
a&&Fsa(a,a.o.zf(!0))},m6=function(){var a=g.Hs("yt-remote-connected-devices")||[];
g.qb(a);return a},Usa=function(a){if(g.$a(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Ic)(a,function(d,e){return 0==e?d:d.substring(c.length)})},Vsa=function(a){g.Gs("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.Hs("yt-remote-device-id");a||(a=i6(),g.Gs("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.Za(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.Za(a,b);g.Is()&&g.sb(a,b);a=Usa(a);if(g.$a(a))try{g.sr("remote_sid")}catch(c){}else try{g.rr("remote_sid",a.join(","),-1)}catch(c){}},Wsa=function(){return g.Hs("yt-remote-session-browser-channel")},Xsa=function(){return g.Hs("yt-remote-local-screens")||[]},Ysa=function(){g.Gs("yt-remote-lounge-token-expiration",!0,86400)},Zsa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Ic)(Xsa(),function(d){return d.loungeToken}),c=(0,g.Ic)(a,function(d){return d.loungeToken});
(0,g.si)(c,function(d){return!g.Za(b,d)})&&Ysa();
g.Gs("yt-remote-local-screens",a,31536E3)},$sa=function(a,b){g.Gs("yt-remote-session-browser-channel",a);
g.Gs("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.Za(c,d)||c.push(d);Vsa(c);p6()},q6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
p6();a=m6();g.cb(a,o6());Vsa(a)},ata=function(){if(!r6){var a=g.go();
a&&(r6=new g.Qn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},bta=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},cta=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?dta(a.shift(),function(){s6(a)}):t6()},eta=function(a){return"chrome-extension://"+a+"/cast_sender.js"},dta=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=cta();
a&&a(!1,"No cast extension found")},gta=function(){if(fta){var a=2,b=cta(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;dta("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},hta=function(){gta();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(a,b,c){g.A.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.fd=b;this.B=(0,g.x)(this.zE,this);this.o=!1;this.u=0;this.w=this.Ia=null;this.A=[]},v6=function(a,b,c){g.A.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.fd=b;this.u=(0,g.x)(this.AE,this);this.o=[]},w6=function(a){a.Ia=g.yf(a.u,a.fd);
a.w.apply(null,a.o)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Isa(a)},y6=function(){},z6=function(){},ita=function(){},kta=function(a){return(a=jta(a))?new ActiveXObject(a):new XMLHttpRequest},jta=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.x1(this);this.u=new g.xf;this.u.setInterval(250)},mta=function(a,b,c){a.Gi=1;
a.og=Z5(b.clone());a.Wh=c;a.C=!0;lta(a,null)},B6=function(a,b,c,d,e){a.Gi=1;
a.og=Z5(b.clone());a.Wh=null;a.C=c;e&&(a.XA=!1);lta(a,d)},lta=function(a,b){a.rj=(0,g.H)();
C6(a);a.Wg=a.og.clone();$5(a.Wg,"t",a.F);a.Ol=0;a.Cc=a.o.Vp(a.o.Al()?b:null);0<a.Fq&&(a.xo=new v6((0,g.x)(a.cC,a,a.Cc),a.Fq));a.A.ga(a.Cc,"readystatechange",a.BN);var c=a.xh?g.ac(a.xh):{};a.Wh?(a.Zo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Cc.send(a.Wg,a.Zo,a.Wh,c)):(a.Zo="GET",a.XA&&!g.Nd&&(c.Connection="close"),a.Cc.send(a.Wg,a.Zo,null,c));a.o.Je(1)},pta=function(a,b,c){for(var d=!0;!a.ih&&a.Ol<c.length;){var e=nta(a,c);
if(e==D6){4==b&&(a.Ag=4,E6(15),d=!1);break}else if(e==ota){a.Ag=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.Ag=1,E6(17),d=!1);a.Ke=a.Ke&&d;d||(G6(a),H6(a))},nta=function(a,b){var c=a.Ol,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return ota;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Ol=d+c;return e},rta=function(a,b){a.rj=(0,g.H)();
C6(a);var c=b?window.location.hostname:"";a.Wg=a.og.clone();Y5(a.Wg,"DOMAIN",c);Y5(a.Wg,"t",a.F);try{a.Oe=new ActiveXObject("htmlfile")}catch(n){G6(a);a.Ag=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in qta)k=I6[l]=qta[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Vc(g.qc("b/12014412"),d+"</body></html>");a.Oe.open();a.Oe.write(g.Qc(c));a.Oe.close();a.Oe.parentWindow.m=(0,g.x)(a.UM,a);a.Oe.parentWindow.d=(0,g.x)(a.gA,a,!0);a.Oe.parentWindow.rpcClose=(0,g.x)(a.gA,a,!1);c=a.Oe.createElement("DIV");a.Oe.parentWindow.document.body.appendChild(c);d=g.Cc(a.Wg.toString());d=g.bd(g.Ac(d));d=g.Vc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Wc(c,d);a.o.Je(1)},C6=function(a){a.Yt=(0,g.H)()+a.B;
sta(a,a.B)},sta=function(a,b){if(null!=a.Fj)throw Error("WatchDog timer not null");
a.Fj=J6((0,g.x)(a.bN,a),b)},K6=function(a){a.Fj&&(g.v.clearTimeout(a.Fj),a.Fj=null)},H6=function(a){a.o.Mw()||a.ih||a.o.oo(a)},G6=function(a){K6(a);
g.je(a.xo);a.xo=null;a.u.stop();g.z1(a.A);if(a.Cc){var b=a.Cc;a.Cc=null;b.abort();b.dispose()}a.Oe&&(a.Oe=null)},F6=function(a,b){try{a.o.aA(a,b),a.o.Je(4)}catch(c){}},uta=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;tta(a,b,function(k){k?c(!0):g.v.setTimeout(function(){uta(a,b,c,d,f)},f)})}},tta=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Hsa(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},vta=function(a){this.o=a;
this.u=new y6},wta=function(a){var b=M6(a.o,a.Pj,"/mail/images/cleardot.gif");
Z5(b);uta(b.toString(),5E3,(0,g.x)(a.wD,a),3,2E3);a.Je(1)},O6=function(a){var b=a.o.H;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.Gd=new A6(a,void 0,void 0,void 0),a.Gd.xh=a.Dq,b=a.o,b=M6(b,b.Al()?a.mk:null,a.Eq),E6(5),!g.Ld||g.pd(10))$5(b,"TYPE","xmlhttp"),B6(a.Gd,b,!1,a.mk,!1);else{$5(b,"TYPE","html");var c=a.Gd;a=!!a.mk;c.Gi=3;c.og=Z5(b.clone());rta(c,a)}},P6=function(a){g.Je.call(this);
this.headers=new g.Sm;this.T=a||null;this.w=!1;this.O=this.o=null;this.da=this.H="";this.C=0;this.A="";this.B=this.Z=this.G=this.U=!1;this.F=0;this.M=null;this.na="";this.J=this.Y=!1},xta=function(a){return g.Ld&&g.od(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},yta=function(a){return"content-type"==a.toLowerCase()},Ata=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;zta(a);Q6(a)},zta=function(a){a.U||(a.U=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Cta=function(a){if(a.w&&"undefined"!=typeof g.F1)if(a.O[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.yf(a.Ow,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.H));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!Bta.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";zta(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){Dta(a);
var c=a.o,d=a.O[0]?g.Fa:null;a.o=null;a.O=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Dta=function(a){a.o&&a.J&&(a.o.ontimeout=null);
a.M&&(g.v.clearTimeout(a.M),a.M=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.da+" "+a.H+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new y6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},Eta=function(a,b){this.o=a;
this.map=b;this.context=null},Fta=function(a){g.le.call(this,"statevent",a)},Gta=function(a,b){g.le.call(this,"timingevent",a);
this.size=b},Hta=function(a){g.le.call(this,"serverreachability",a)},Kta=function(a){Ita(a);
if(3==a.o){var b=a.Zk++,c=a.Sm.clone();Y5(c,"SID",a.w);Y5(c,"RID",b);Y5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.w,b,void 0);b.Gi=2;b.og=Z5(c.clone());Hsa(new Image,b.og.toString());b.rj=(0,g.H)();C6(b)}Jta(a)},Lta=function(a){a.SD(1,0);
a.Sm=M6(a,null,a.Cq);W6(a)},Ita=function(a){a.tg&&(a.tg.abort(),a.tg=null);
a.Yb&&(a.Yb.cancel(),a.Yb=null);a.Cf&&(g.v.clearTimeout(a.Cf),a.Cf=null);X6(a);a.yd&&(a.yd.cancel(),a.yd=null);a.xg&&(g.v.clearTimeout(a.xg),a.xg=null)},Mta=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new Eta(a.nJ++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.yd||a.xg||(a.xg=J6((0,g.x)(a.fA,a),0),a.zi=0)},Ota=function(a,b){if(1==a.o){if(!b){a.Zk=Math.floor(1E5*Math.random());
var c=a.Zk++,d=new A6(a,"",c,void 0);d.xh=null;var e=Y6(a),f=a.Sm.clone();Y5(f,"RID",c);Y5(f,"CVER","1");V6(a,f);mta(d,f,e);a.yd=d;a.o=2}}else 3==a.o&&(b?Nta(a,b):0==a.u.length||a.yd||Nta(a))},Nta=function(a,b){if(b)if(6<a.jh){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.Zk-1;var d=Y6(a)}else c=b.G,d=b.Wh;else c=a.Zk++,d=Y6(a);var e=a.Sm.clone();Y5(e,"SID",a.w);Y5(e,"RID",c);Y5(e,"AID",a.Ti);V6(a,e);c=new A6(a,a.w,c,a.zi+1);c.xh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yd=c;mta(c,e,d)},V6=function(a,b){if(a.bd){var c=a.bd.jw();
c&&g.Lb(c,function(d,e){Y5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.jh&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.jh?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},Pta=function(a){a.Yb||a.Cf||(a.F=1,a.Cf=J6((0,g.x)(a.eA,a),0),a.si=0)},Z6=function(a){if(a.Yb||a.Cf||3<=a.si)return!1;
a.F++;a.Cf=J6((0,g.x)(a.eA,a),Qta(a,a.si));a.si++;return!0},N6=function(a,b,c){a.Xo=c;
a.We=b.Pf;a.C||Lta(a)},X6=function(a){null!=a.mh&&(g.v.clearTimeout(a.mh),a.mh=null)},Qta=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.bd&&(c=null);var d=(0,g.x)(a.kO,a);c||(c=new g.Vm("//www.google.com/images/cleardot.gif"),Z5(c));tta(c.toString(),1E4,d)}else E6(2);Rta(a,b)},Rta=function(a,b){a.o=0;
a.bd&&a.bd.yv(b);Jta(a);Ita(a)},Jta=function(a){a.o=0;
a.We=-1;if(a.bd)if(0==a.A.length&&0==a.u.length)a.bd.Np();else{g.gb(a.A);var b=g.gb(a.u);a.A.length=0;a.u.length=0;a.bd.Np(b)}},M6=function(a,b,c){var d=g.cn(c);
if(""!=d.o)b&&g.Xm(d,b+"."+d.o),g.Ym(d,d.B);else{var e=window.location;d=Lsa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.bk&&g.Lb(a.bk,function(f,k){Y5(d,k,f)});
Y5(d,"VER",a.jh);V6(a,d);return d},J6=function(a,b){if(!g.Ka(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new Fta(a7,a))},Sta=function(){},Tta=function(){this.o=[];
this.u=[]},Uta=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.A.call(this);
this.o=new g.J(this.KM,0,this);g.C(this,this.o);this.fd=5E3;this.u=0;if(g.Ka(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ka(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.M=a;
this.C=b;this.w=new g.Pn;this.u=new b7(this.ON,this);this.o=null;this.qb=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.J=c||!1},Vta=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Xo,sessionId:a.o.w,arrayId:a.o.Ti}},Wta=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&Ota(a.o),Kta(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},Xta=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.bh(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Oa(a.A,d,!0),onError:g.Oa(a.w,e),Cd:g.Oa(a.B,e)};c&&(a.wb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.aq(b,a)},aua=function(){var a=Yta;
Zta();h7.push(a);$ta(h7)},i7=function(a,b){Zta();
var c=h7,d=bua(a,String(b));g.$a(c)?cua(d):($ta(c),(0,g.z)(c,function(e){e(d)}))},Zta=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ea("yt.mdx.remote.debug.handlers_",h7,void 0))},cua=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},$ta=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},bua=function(a,b){var c=((0,g.H)()-dua)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.Q.call(this);
this.F=a;this.o=[]},eua=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},fua=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Yd)(a.o,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=eua(a,b[d])||c;return c},gua=function(a,b){var c=a.o.length;
a.o=(0,g.Yd)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.Q.call(this);
this.C=a;this.B=b;this.w=c;this.A=d;this.u=0;this.o=null;this.Ia=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+h6(this.o))},hua=function(a){if(a.o.length){var b=(0,g.Ic)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.JE,a),(0,g.x)(a.IE,a))}},o7=function(a){var b=Rsa(Xsa());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return fua(a,b)},q7=function(a,b){Zsa((0,g.Ic)(a.o,Psa));
b&&Ysa()},s7=function(a,b){g.Q.call(this);
this.C=b;var c=g.Hs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Za(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.Nk(this.o))},iua=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(a6(b)!=a6(a.o))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Nk(a.o)),a.o=b,a.R("screenChange"));jua(a)},u7=function(a){isNaN(a.w)||g.cp(a.w);
a.w=g.ap((0,g.x)(a.it,a),0<a.A&&a.A<(0,g.H)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},kua=function(a){var b={};
(0,g.z)(a.C(),function(c){c.token?b[c.token]=c.id:this.Qb("Requesting availability of screen w/o lounge token.")});
return b},jua=function(a){a=g.Sb(g.Mb(a.o,function(b){return b}));
g.qb(a);a.length?g.Gs("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};lua(this)},nua=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.Wd();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=w7(a,k);iua(a.u,l,function(m){e(m?l:null)})}else c?mua(a,c,(0,g.x)(function(m){var n=w7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));iua(this.u,n,function(q){e(q?n:null)})},a),f):e(null)},oua=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},mua=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={wb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.aq(f7(a.C,"/pairing/get_lounge_token_batch"),e)},pua=function(a){a.o=a.w.Wd();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},lua=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.RE,a));pua(a);a.A=Rsa(g.Hs("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+h6(a.A));a.u=new s7(a.C,(0,g.x)(a.Wd,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.R("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Gs("yt-remote-automatic-screen-cache",(0,g.Ic)(a.A,Psa)));x7(a);a.B[b.uuid]=b.id;g.Gs("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.Hs("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.Q.call(this);
this.O=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.O,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.UO,this);this.B=(0,g.x)(this.kN,this);this.A=g.ap((0,g.x)(function(){qua(this,null)},this),12E4)},rua=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Nk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Fa,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Nk(b))},qua=function(a,b){g.cp(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.qo,a),d=(0,g.x)(a.be,a);a.Ew(b,c,d,5)}}else a.be(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.M="";this.T=c;this.B=null;this.F=g.Fa;this.C=NaN;this.J=(0,g.x)(this.XO,this);this.o=g.Fa},sua=function(a){a.o=a.H.iC(a.M,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Fa;
this.qo(b)},a),(0,g.x)(function(b){this.o=g.Fa;
this.be(b)},a))},tua=function(a){var b={};
b.pairingCode=a.M;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}ata()&&(b.env_useStageMdx=1);return g.$g(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.ap((0,g.x)(this.Ui,this,null),150)},D7=function(a,b,c,d){g.Q.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.UL,this)},uua=function(a,b){return b?g.Va(a.w,function(c){return f6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},Yta=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.je(a.o),(a.o=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.u):a.R("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.dA,a,b)),b.w?a.R("yt-remote-cast2-session-change",b.w):c&&a.o.Ui(null)):a.R("yt-remote-cast2-session-change",null))},vua=function(a){var b=a.u.hC(),c=a.o&&a.o.u;
a=(0,g.Ic)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=uua(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Bua=function(a,b,c,d,e,f,k){wua()?xua(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?yua(a,c):(window.__onGCastApiAvailable=function(l,m){l?yua(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),zua(),c(!1))},d?g.np("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?hta():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(gta(),s6(Aua.map(eta))))):H7("Cannot initialize because not running Chrome")},zua=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ea("yt.mdx.remote.cloudview.instance_",null,void 0);Cua(!1);g.ip(M7);M7.length=0},N7=function(){return!!g.Hs("yt-remote-cast-installed")},Dua=function(){var a=g.Hs("yt-remote-cast-receiver");
return a?a.friendlyName:null},Eua=function(){H7("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},Fua=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.hp("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},wua=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Vv||a},Gua=function(a,b){L7().init(a,b)},xua=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Gs("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.Gs("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.Gs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ea("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},yua=function(a,b){K7(!0);
I7(!1);Gua(a,function(c){c?(Cua(!0),g.kp("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),zua());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.Gs("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},Cua=function(a){H7("setApiReady_ "+a);
g.Ea("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ea("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.Xe=!1;this.H=this.G=this.u=this.A=0;this.w=NaN;this.B=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Xe=!1;a.hasNext=!1;a.F=0;a.C=(0,g.H)();a.A=0;a.u=0;a.G=0;a.H=0;a.w=NaN;a.B=!1},T7=function(a){return 1==a.playerState?((0,g.H)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.H)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.o);b.hasPrevious=a.Xe;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.A;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.w;return b},Z7=function(a,b){g.Q.call(this);
this.o=0;this.A=a;this.C=[];this.B=new Tta;this.w=this.u=null;this.H=(0,g.x)(this.VJ,this);this.F=(0,g.x)(this.dl,this);this.G=(0,g.x)(this.UJ,this);this.M=(0,g.x)(this.hK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.cu,this),Hua(this))):c=3;0!=c&&(b?this.cu(c):g.ap((0,g.x)(function(){this.cu(c)},this),0));
var d=Fua();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.M)},$7=function(a){return new R7(a.A.getPlayerContextData())},Hua=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Oa(this.RL,b),this))},a)},Iua=function(a){(0,g.z)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){Iua(a);
a.A.setPlayerContextData(X7(b));Hua(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.F),a.dl(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.F),a.w.media.length&&a.dl(a.w.media[0]))},Jua=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Qb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Qb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.Q.call(this);
this.B=NaN;this.J=!1;this.G=this.F=this.H=this.M=NaN;this.O=[];this.A=this.C=this.w=this.Sa=this.o=null;this.U=a;this.O.push(g.Vq(window,"beforeunload",(0,g.x)(this.CE,this)));this.u=[];this.Sa=new R7;this.T=b.id;this.o=Kua(this,c);this.o.subscribe("handlerOpened",this.ZJ,this);this.o.subscribe("handlerClosed",this.WJ,this);this.o.subscribe("handlerError",this.XJ,this);this.o.subscribe("handlerMessage",this.YJ,this);Xta(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Sa.videoId;
g.Is()&&g.Gs("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},Kua=function(a,b){return new c7(f7(a.U,"/bc"),b)},h8=function(a,b){a.R("proxyStateChange",b)},Lua=function(a){a.B=g.ap((0,g.x)(function(){g8("Connecting timeout");
this.yi(1)},a),2E4)},i8=function(a){g.cp(a.B);
a.B=NaN},j8=function(a){g.cp(a.M);
a.M=NaN},Mua=function(a){k8(a);
a.H=g.ap((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.cp(a.H);
a.H=NaN},Oua=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.Cw()&&a.Sa.reset(),h8(a,1),l8(a,"getNowPlaying"),Nua(a)):a.yi(1)},Pua=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Sa.videoId&&(g.Yb(b.params)?a.Sa.o=null:a.Sa.o=b.params,a.R("remotePlayerChange"))},Qua=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Sa.listId=b.params.listId||a.Sa.listId;W7(a.Sa,c,d);a.R("remoteQueueChange")},Sua=function(a,b){b.params=b.params||{};
Qua(a,b);Rua(a,b);a.R("autoplayDismissed")},Rua=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Sa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Sa.playerState&&(c=-1E3);a.Sa.playerState=c;c=Number(b.params.loadedTime);a.Sa.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Sa.G=isNaN(c)?0:c;c=a.Sa;var d=Number(b.params.liveIngestionTime);c.w=d;c.B=isNaN(d)?!1:!0;c=a.Sa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.A=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Sa.playerState?Mua(a):k8(a);a.R("remotePlayerChange")},Tua=function(a,b){if(-1E3!=
a.Sa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Sa.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Sa,isNaN(c)?0:c);a.R("remotePlayerChange")}},Uua=function(a,b){var c="true"==b.params.muted;
a.Sa.volume=parseInt(b.params.volume,10);a.Sa.muted=c;a.R("remotePlayerChange")},Vua=function(a,b){a.C=b.params.videoId;
a.R("nowAutoplaying",parseInt(b.params.timeout,10))},Wua=function(a,b){var c="true"==b.params.hasNext;
a.Sa.Xe="true"==b.params.hasPrevious;a.Sa.hasNext=c;a.R("previousNextChange")},Nua=function(a){g.cp(a.G);
a.G=g.ap((0,g.x)(a.yi,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Nk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.dd=a;this.u=[];this.u.push(this.dd.$_s("screenChange",(0,g.x)(this.SO,this)));this.u.push(this.dd.$_s("onlineScreenChange",(0,g.x)(this.wL,this)))},ava=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.N("MDX_CONFIG")||b;Tsa();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),ata()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ea("yt.mdx.remote.deferredProxies_",o8,void 0));Xua();var c=p8();if(!c){var d=new v7(n8);g.Ea("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Bua(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ea("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Nk(b)),s8.push(g.hp("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),s8.push(g.hp("yt-remote-cast2-receiver-selected",function(){t8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.hp("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.hp("yt-remote-cast2-session-change",Yua)),s8.push(g.hp("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),Eua())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.Sp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.Nk(a)),Zua(a),c.start(),q8()||$ua())},cva=function(){var a=bva();
N7()&&g.Hs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},bva=function(){var a=p8().dd.$_gos();
var b=w8();b&&x8()&&(j6(a,b)||a.push(b));return Ssa(a)},y8=function(){var a=dva();
!a&&N7()&&Dua()&&(a={key:"cast-selector-receiver",name:Dua()});return a},dva=function(){var a=bva(),b=w8();
b||(b=u8());return g.Va(a,function(c){return b&&f6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().Wd();return k6(b,a)},Yua=function(a){r8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},eva=function(a){g.Ea("yt.mdx.remote.currentScreenId_",a,void 0)},fva=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ea("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||eva("");g.Ea("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.z)(o8,function(c){c(a)}),o8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},u8=function(){var a=g.Is();
if(!a)return null;var b=p8().Wd();return k6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{eva(a.id);var c=new f8(n8,a,v8());c.connect(b,fva());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},$ua=function(){var a=u8();
a?(r8("Resume connection to: "+g6(a)),A8(a,0)):(q6(),Eua(),r8("Skipping connecting because no session screen found."))},Xua=function(){var a=v8();
if(g.Yb(a)){a=o6();var b=g.Hs("yt-remote-session-name")||"",c=g.Hs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ea("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Zua=function(a){a?(g.Gs("yt-remote-session-app",a.app),g.Gs("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ea("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.A.call(this);
this.B=a;this.u=b;this.w=new g.P(this);g.C(this,this.w);this.w.L(b,"onCaptionsTrackListChanged",this.SK);this.w.L(b,"captionschanged",this.TJ);this.w.L(b,"captionssettingschanged",this.sB);this.w.L(b,"videoplayerreset",this.ro);this.w.L(b,"mdxautoplaycancel",this.vD);this.T=this.w.L(b,"onVolumeChange",this.Lz);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.Zz,this);c.subscribe("remotePlayerChange",this.jl,this);c.subscribe("remoteQueueChange",this.ro,this);c.subscribe("autoplayUpNext",this.Bz,
this);c.subscribe("previousNextChange",this.Wz,this);c.subscribe("nowAutoplaying",this.Sz,this);c.subscribe("autoplayDismissed",this.Az,this);this.suggestion=null;this.H=new g.BD(64);this.A=new g.J(this.oB,500,this);g.C(this,this.A);this.C=new g.J(this.pB,1E3,this);g.C(this,this.C);this.J=new u6(this.uO,0,this);g.C(this,this.J);this.F={};this.O=new g.J(this.UB,1E3,this);g.C(this,this.O);this.M=new v6(this.uH,1E3,this);g.C(this,this.M);this.U=g.Fa;this.sB();this.ro();this.jl()},H8=function(a,b){var c=
a.B,d=a.u.getVideoData().lengthSeconds;
c.O=b||0;c.player.R("progresssync",b,d)},gva=function(a){H8(a,0);
a.A.stop();I8(a,new g.BD(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.dc(c,b));a.o.dB(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.Ua;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.Ze,g.KB(c));I8(a,new g.BD(1))},hva=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{QS:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.HD(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.US(a.u.app,d);a.H=b;iva(a.B,c,b)}},M8=function(){g.V.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",N:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-popup-title",V:"You're signed out"},{D:"div",I:"ytp-mdx-popup-description",V:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Cancel"},{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
V:"Confirm"}]}]}]});this.u=new g.gM(this,250);g.C(this,this.u);this.C=this.o["ytp-mdx-privacy-popup-cancel"];this.L(this.C,"click",this.w);this.A=this.o["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},N8=function(a){g.V.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.iM()]},{D:"div",I:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.u=new g.gM(this,250);g.C(this,this.u);this.w=a;this.L(a,"presentingplayerstatechange",this.A);jva(this,g.vL(a))},jva=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.W(b,128)?g.MM("Error on $RECEIVER_NAME",c):g.ID(b)||g.W(b,4)?g.MM("Playing on $RECEIVER_NAME",c):g.MM("Connected to $RECEIVER_NAME",c);a.ia("statustext",c);a.u.show()}else a.u.hide()},O8=function(a,b){g.vO.call(this,"Play on",0,a,b);
this.u=a;this.C={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},P8=function(a){g.EP.call(this,a);
this.u={key:i6(),name:"This computer"};this.B=null;this.A=[];this.T=this.o=null;this.M=[this.u];this.w=this.u;this.F=new g.BD(64);this.O=0;this.H=-1;this.C=null;if(!g.Xx(this.player.P())){a=this.player;var b=g.hD(a);b&&(b=b.Sk())&&(b=new O8(a,b),g.C(this,b));b=new N8(a);g.C(this,b);g.NL(a,b.element,4);this.C=new M8;g.C(this,this.C);g.NL(a,this.C.element,4);this.J=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},iva=function(a,b,c){a.F=
c;
a.player.R("presentingplayerstatechange",new g.ND(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.R(a.player.P().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.N("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.N("SESSION_INDEX")&&!g.N("LOGGED_IN")))||a.J||!a.C);if(c?0:a.player.P().zh()||"WEB_EMBEDDED_PLAYER"==a.player.P().deviceParams.c)g.ID(g.vL(a.player))?a.player.pauseVideo():(a.G=(0,g.x)(a.pN,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.u.show(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(!d&&!e||(2==a.player.app.U||1==a.player.app.U)&&g.R(a.player.P().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.wa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ze,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=g.KB(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+
g.Nk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?c6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().Wd(),(c=k6(c,b.key))&&A8(c,1))}},qta={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},kva={},Osa={vP:"atp",aS:"ska",PR:"que",iR:"mus",ZR:"sus",uQ:"dsp",WR:"seq"};
d6.prototype.ug=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
var r6,n6="",fta=bta("loadCastFramework")||bta("loadCastApplicationFramework"),Aua=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Qa(u6,g.A);g.h=u6.prototype;g.h.yE=function(a){this.A=arguments;this.o=!1;this.Ia?this.w=(0,g.H)()+this.fd:this.Ia=g.yf(this.B,this.fd)};
g.h.stop=function(){this.Ia&&(g.v.clearTimeout(this.Ia),this.Ia=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.X=function(){this.stop();u6.Db.X.call(this)};
g.h.zE=function(){this.w?(this.Ia=g.yf(this.B,this.w-(0,g.H)()),this.w=null):(this.Ia=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.Qa(v6,g.A);g.h=v6.prototype;g.h.Fi=!1;g.h.lk=0;g.h.Ia=null;g.h.Lw=function(a){this.o=arguments;this.Ia||this.lk?this.Fi=!0:w6(this)};
g.h.stop=function(){this.Ia&&(g.v.clearTimeout(this.Ia),this.Ia=null,this.Fi=!1,this.o=[])};
g.h.pause=function(){this.lk++};
g.h.resume=function(){this.lk--;this.lk||!this.Fi||this.Ia||(this.Fi=!1,w6(this))};
g.h.X=function(){v6.Db.X.call(this);this.stop()};
g.h.AE=function(){this.Ia=null;this.Fi&&!this.lk&&(this.Fi=!1,w6(this))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},jta(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Qa(ita,z6);S8=new ita;g.h=A6.prototype;g.h.xh=null;g.h.Ke=!1;g.h.Fj=null;g.h.Yt=null;g.h.rj=null;g.h.Gi=null;g.h.og=null;g.h.Wg=null;g.h.Wh=null;g.h.Cc=null;g.h.Ol=0;g.h.Oe=null;g.h.Zo=null;g.h.Ag=null;g.h.nk=-1;g.h.XA=!0;g.h.ih=!1;g.h.Fq=0;g.h.xo=null;var ota={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.BN=function(a){a=a.target;var b=this.xo;b&&3==R6(a)?b.Lw():this.cC(a)};
g.h.cC=function(a){try{if(a==this.Cc)a:{var b=R6(this.Cc),c=this.Cc.C,d=this.Cc.getStatus();if(g.Ld&&!g.pd(10)||g.Nd&&!g.od("420+")){if(4>b)break a}else if(3>b||3==b&&!g.th&&!T6(this.Cc))break a;this.ih||4!=b||7==c||(8==c||0>=d?this.o.Je(3):this.o.Je(2));K6(this);var e=this.Cc.getStatus();this.nk=e;var f=T6(this.Cc);(this.Ke=200==e)?(4==b&&G6(this),this.C?(pta(this,b,f),g.th&&this.Ke&&3==b&&(this.A.ga(this.u,"tick",this.vN),this.u.start())):F6(this,f),this.Ke&&!this.ih&&(4==b?this.o.oo(this):(this.Ke=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Ag=3,E6(13)):(this.Ag=0,E6(14)),G6(this),H6(this))}}catch(k){this.Cc&&T6(this.Cc)}finally{}};
g.h.vN=function(){var a=R6(this.Cc),b=T6(this.Cc);this.Ol<b.length&&(K6(this),pta(this,a,b),this.Ke&&4!=a&&C6(this))};
g.h.UM=function(a){J6((0,g.x)(this.TM,this,a),0)};
g.h.TM=function(a){this.ih||(K6(this),F6(this,a),C6(this))};
g.h.gA=function(a){J6((0,g.x)(this.SM,this,a),0)};
g.h.SM=function(a){this.ih||(G6(this),this.Ke=a,this.o.oo(this),this.o.Je(4))};
g.h.cancel=function(){this.ih=!0;G6(this)};
g.h.bN=function(){this.Fj=null;var a=(0,g.H)();0<=a-this.Yt?(2!=this.Gi&&this.o.Je(3),G6(this),this.Ag=2,E6(18),H6(this)):sta(this,this.Yt-a)};
g.h.getLastError=function(){return this.Ag};g.h=vta.prototype;g.h.Dq=null;g.h.Gd=null;g.h.yo=!1;g.h.Nw=null;g.h.Qm=null;g.h.rr=null;g.h.Eq=null;g.h.oe=null;g.h.Pf=-1;g.h.mk=null;g.h.Pj=null;g.h.connect=function(a){this.Eq=a;a=M6(this.o,null,this.Eq);E6(3);this.Nw=(0,g.H)();var b=this.o.G;null!=b?(this.mk=b[0],(this.Pj=b[1])?(this.oe=1,wta(this)):(this.oe=2,O6(this))):($5(a,"MODE","init"),this.Gd=new A6(this,void 0,void 0,void 0),this.Gd.xh=this.Dq,B6(this.Gd,a,!1,null,!0),this.oe=0)};
g.h.wD=function(a){if(a)this.oe=2,O6(this);else{E6(4);var b=this.o;b.We=b.tg.Pf;$6(b,9)}a&&this.Je(2)};
g.h.Vp=function(a){return this.o.Vp(a)};
g.h.abort=function(){this.Gd&&(this.Gd.cancel(),this.Gd=null);this.Pf=-1};
g.h.Mw=function(){return!1};
g.h.aA=function(a,b){this.Pf=a.nk;if(0==this.oe)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.We=this.Pf;$6(c,2);return}this.mk=c[0];this.Pj=c[1]}else c=this.o,c.We=this.Pf,$6(c,2);else if(2==this.oe)if(this.yo)E6(7),this.rr=(0,g.H)();else if("11111"==b){if(E6(6),this.yo=!0,this.Qm=(0,g.H)(),c=this.Qm-this.Nw,!g.Ld||g.pd(10)||500>c)this.Pf=200,this.Gd.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.Qm=this.rr=(0,g.H)(),this.yo=!1};
g.h.oo=function(){this.Pf=this.Gd.nk;if(this.Gd.Ke)0==this.oe?this.Pj?(this.oe=1,wta(this)):(this.oe=2,O6(this)):2==this.oe&&((!g.Ld||g.pd(10)?!this.yo:200>this.rr-this.Qm)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.oe?E6(9):2==this.oe&&E6(10);var a=this.o;this.Gd.getLastError();a.We=this.Pf;$6(a,2)}};
g.h.Al=function(){return this.o.Al()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Je=function(a){this.o.Je(a)};g.Qa(P6,g.Je);var Bta=/^https?$/i,lva=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.da=b;this.U=!1;this.w=!0;this.o=this.T?kta(this.T):kta(S8);this.O=this.T?this.T.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.Ow,this);try{b6(S6(this,"Opening Xhr")),this.Z=!0,this.o.open(b,String(a),!0),this.Z=!1}catch(f){b6(S6(this,"Error opening Xhr: "+f.message));Ata(this,f);return}a=c||
"";var e=this.headers.clone();d&&Ksa(d,function(f,k){e.set(k,f)});
d=g.Va(e.le(),yta);c=g.v.FormData&&a instanceof g.v.FormData;!g.Za(lva,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.na&&(this.o.responseType=this.na);"withCredentials"in this.o&&this.o.withCredentials!==this.Y&&(this.o.withCredentials=this.Y);try{Dta(this),0<this.F&&(this.J=xta(this.o),b6(S6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.J)),this.J?(this.o.timeout=this.F,this.o.ontimeout=(0,g.x)(this.Pw,this)):this.M=g.yf(this.Pw,this.F,this)),b6(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){b6(S6(this,"Send error: "+f.message)),Ata(this,f)}};
g.h.Pw=function(){"undefined"!=typeof g.F1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.X=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.Db.X.call(this)};
g.h.Ow=function(){this.ka()||(this.Z||this.G||this.B?Cta(this):this.TL())};
g.h.TL=function(){Cta(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.bk=null;g.h.yd=null;g.h.Yb=null;g.h.Cq=null;g.h.Sm=null;g.h.fv=null;g.h.gn=null;g.h.Zk=0;g.h.nJ=0;g.h.bd=null;g.h.xg=null;g.h.Cf=null;g.h.mh=null;g.h.tg=null;g.h.Xo=null;g.h.Ti=-1;g.h.Ax=-1;g.h.We=-1;g.h.zi=0;g.h.si=0;g.h.jh=8;var a7=new g.Je;g.Qa(Fta,g.le);g.Qa(Gta,g.le);g.Qa(Hta,g.le);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Cq=b;this.bk=c||{};d&&void 0!==e&&(this.bk.OSID=d,this.bk.OAID=e);this.C?(J6((0,g.x)(this.Ev,this,a),100),Lta(this)):this.Ev(a)};
g.h.Ev=function(a){this.tg=new vta(this);this.tg.Dq=null;this.tg.u=this.B;this.tg.connect(a)};
g.h.Mw=function(){return 0==this.o};
g.h.fA=function(a){this.xg=null;Ota(this,a)};
g.h.eA=function(){this.Cf=null;this.Yb=new A6(this,this.w,"rpc",this.F);this.Yb.xh=null;this.Yb.Fq=0;var a=this.fv.clone();Y5(a,"RID","rpc");Y5(a,"SID",this.w);Y5(a,"CI",this.Xo?"0":"1");Y5(a,"AID",this.Ti);V6(this,a);if(!g.Ld||g.pd(10))Y5(a,"TYPE","xmlhttp"),B6(this.Yb,a,!0,this.gn,!1);else{Y5(a,"TYPE","html");var b=this.Yb,c=!!this.gn;b.Gi=3;b.og=Z5(a.clone());rta(b,c)}};
g.h.aA=function(a,b){if(0!=this.o&&(this.Yb==a||this.yd==a))if(this.We=a.nk,this.yd==a&&3==this.o)if(7<this.jh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Ia(c)&&3==c.length)if(0==c[0])a:{if(!this.Cf){if(this.Yb)if(this.Yb.rj+3E3<this.yd.rj)X6(this),this.Yb.cancel(),this.Yb=null;else break a;Z6(this);E6(19)}}else this.Ax=c[1],0<this.Ax-this.Ti&&37500>c[2]&&this.Xo&&0==this.si&&!this.mh&&(this.mh=J6((0,g.x)(this.PJ,this),6E3));else $6(this,11)}else b!=kva.SP.o&&$6(this,11);else if(this.Yb==a&&
X6(this),!g.xb(b)){c=this.B.parse(b);g.Ia(c);for(var d=0;d<c.length;d++){var e=c[d];this.Ti=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.gn=e[2],e=e[3],null!=e?this.jh=e:this.jh=6,this.o=3,this.bd&&this.bd.Av(),this.fv=M6(this,this.Al()?this.gn:null,this.Cq),Pta(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.bd&&this.bd.zv(e),this.si=0)}}};
g.h.PJ=function(){null!=this.mh&&(this.mh=null,this.Yb.cancel(),this.Yb=null,Z6(this),E6(20))};
g.h.oo=function(a){if(this.Yb==a){X6(this);this.Yb=null;var b=2}else if(this.yd==a)this.yd=null,b=1;else return;this.We=a.nk;if(0!=this.o)if(a.Ke)1==b?(b=(0,g.H)()-a.rj,a7.dispatchEvent(new Gta(a7,a.Wh?a.Wh.length:0,b,this.zi)),W6(this),this.A.length=0):Pta(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.We)){if(d=1==b)this.yd||this.xg||1==this.o||2<=this.zi?d=!1:(this.xg=J6((0,g.x)(this.fA,this,a),Qta(this,this.zi)),this.zi++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.SD=function(a){if(!g.Za(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.kO=function(a){a?E6(2):(E6(1),Rta(this,8))};
g.h.Vp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.Y=!1;return a};
g.h.isActive=function(){return!!this.bd&&this.bd.isActive(this)};
g.h.Je=function(a){a7.dispatchEvent(new Hta(a7,a))};
g.h.Al=function(){return!(!g.Ld||g.pd(10))};
g.h=Sta.prototype;g.h.Av=function(){};
g.h.zv=function(){};
g.h.yv=function(){};
g.h.Np=function(){};
g.h.jw=function(){return{}};
g.h.isActive=function(){return!0};g.h=Tta.prototype;g.h.isEmpty=function(){return g.$a(this.o)&&g.$a(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.Za(this.o,a)||g.Za(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Wna)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.u,a)};
g.h.rd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Qa(b7,g.A);g.h=b7.prototype;g.h.KM=function(){this.fd=Math.min(3E5,2*this.fd);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.fd+15E3*Math.random();g.pn(this.o,a);this.u=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.fd=5E3};g.Qa(c7,Sta);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.ff=function(a){return this.w.yh(a)};
g.h.R=function(a,b){return this.w.R.apply(this.w,arguments)};
g.h.dispose=function(){this.qb||(this.qb=!0,g.je(this.w),Wta(this),g.je(this.u),this.u=null)};
g.h.ka=function(){return this.qb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.M+"/test";b=this.M+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.J),e=this.o;e&&(e.bd=null);d.bd=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.Ti):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&Mta(this.o,c)};
g.h.Av=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Mta(this.o,a[b])}this.R("handlerOpened")};
g.h.yv=function(a){var b=2==a&&401==this.o.We;4==a||b||this.u.start();this.R("handlerError",a)};
g.h.Np=function(a){if(!this.u.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.jw=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.dc(a,this.B);return a};
g.h.zv=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),Kta(this.o)):this.R("handlerMessage",new Uta(a[0],a[1]))};
g.h.ON=function(){this.u.isActive();var a=this.o,b=0;a.Yb&&b++;a.yd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var dua=(0,g.H)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Qa(m7,g.Q);m7.prototype.Wd=function(){return this.o};
m7.prototype.contains=function(a){return!!j6(this.o,a)};
m7.prototype.get=function(a){return a?k6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.Q);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ia)&&this.gC()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ia)||(g.cp(this.Ia),this.Ia=NaN)};
g.h.X=function(){this.stop();g.Q.prototype.X.call(this)};
g.h.gC=function(){this.Ia=NaN;this.o=g.aq(f7(this.C,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.x)(this.QO,this),onError:(0,g.x)(this.PO,this),Cd:(0,g.x)(this.RO,this)})};
g.h.QO=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.w;c.name=this.A;this.R("pairingComplete",new e6(c))};
g.h.PO=function(a){this.o=null;a.status&&404==a.status?this.u>=mva.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=mva[this.u],this.Ia=g.ap((0,g.x)(this.gC,this),a),this.u++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.RO=function(){this.o=null;this.R("pairingFailed",Error("Server not responding"))};
var mva=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Qa(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.R("screenChange");!g.Hs("yt-remote-lounge-token-expiration")&&hua(this);g.cp(this.u);this.u=g.ap((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);eua(this,a);q7(this,!1);this.R("screenChange");b(a);a.token||hua(this)};
g.h.remove=function(a,b){var c=o7(this);gua(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.Uo=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.X=function(){g.cp(this.u);p7.Db.X.call(this)};
g.h.JE=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.IE=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.Q);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.Hs("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.H)()-144E5<a?0:a)?u7(this):(this.A=(0,g.H)()+3E5,g.Gs("yt-remote-fast-check-period",this.A),this.it())};
g.h.isEmpty=function(){return g.Yb(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Mb(this.o,function(c,d){return c&&!!k6(a,d)},this);
t7(this,b)};
g.h.X=function(){g.cp(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.Q.prototype.X.call(this)};
g.h.it=function(){g.cp(this.w);this.w=NaN;this.u&&this.u.abort();var a=kua(this);if(a6(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Sb(a).join(",")},(0,g.x)(this.pM,this,a),(0,g.x)(this.oM,this))}else t7(this,{}),u7(this)};
g.h.pM=function(a,b){this.u=null;var c=g.Sb(kua(this));if(g.rb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Qb("Changing Screen set during request."),this.it()};
g.h.oM=function(a){this.Qb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Qb=function(a){i7("OnlineScreenService",a)};g.Qa(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.R("screenChange"),this.u.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.Uo=function(a,b,c,d){this.w.contains(a)?this.w.Uo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.Wd=function(a){return a?this.o:g.fb(this.o,(0,g.Yd)(this.A,function(b){return!this.contains(b)},this))};
g.h.hC=function(){return(0,g.Yd)(this.Wd(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.iC=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.je(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.je(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.TO=function(a,b,c,d){g.aq(f7(this.C,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||oua(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);oua(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Cd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.je(this.w);g.je(this.u);v7.Db.X.call(this)};
g.h.RE=function(){pua(this);this.R("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Qa(y7,g.Q);g.h=y7.prototype;g.h.qo=function(a){this.w=a;this.R("sessionScreen",this.w)};
g.h.be=function(a){this.ka()||(a&&z7(this,""+a),this.w=null,this.R("sessionScreen",null))};
g.h.info=function(a){i7(this.O,a)};
g.h.kC=function(){return null};
g.h.wt=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.wt("");y7.Db.X.call(this)};g.Qa(A7,y7);g.h=A7.prototype;g.h.vt=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);rua(this)};
g.h.Ui=function(a){this.info("launchWithParams no-op for Cast: "+g.Nk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.be()},this),(0,g.x)(function(){this.be(Error("Failed to stop receiver app."))},this)):this.be(Error("Stopping cast device witout session."))};
g.h.wt=g.Fa;g.h.X=function(){this.info("disposeInternal");g.cp(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Db.X.call(this)};
g.h.kN=function(a,b){if(!this.ka())if(b){var c=x6(b);if(g.La(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Nk(c));switch(d){case "mdxSessionStatus":qua(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.Ew=function(a,b,c,d){nua(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.ap((0,g.x)(this.Ew,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.kC=function(){return this.o};
g.h.UO=function(a){this.ka()||a||(z7(this,"Cast session died."),this.be())};g.Qa(B7,y7);g.h=B7.prototype;g.h.vt=function(a){this.A=a;this.A.addUpdateListener(this.J)};
g.h.Ui=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Fa;g.cp(this.C);this.A?this.A.stop((0,g.x)(this.be,this,null),(0,g.x)(this.be,this,"Failed to stop DIAL device.")):this.be()};
g.h.X=function(){this.o();this.o=g.Fa;g.cp(this.C);this.A&&this.A.removeUpdateListener(this.J);this.A=null;B7.Db.X.call(this)};
g.h.XO=function(a){this.ka()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Fa,this.be())};
g.h.Sq=function(a){this.M=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,tua(this));a(b);sua(this)}else this.F=(0,g.x)(function(){g.cp(this.C);this.F=g.Fa;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,tua(this));a(c);sua(this)},this),this.C=g.ap((0,g.x)(function(){this.F()},this),100)};
g.h.kF=function(a,b,c){nua(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.qo(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Sq(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.Sq(b,c)},this))};g.Qa(C7,y7);C7.prototype.stop=function(){this.be()};
C7.prototype.vt=g.Fa;C7.prototype.Ui=function(){g.cp(this.o);this.o=NaN;var a=k6(this.H.Wd(),this.u.label);a?this.qo(a):this.be(Error("No such screen"))};
C7.prototype.X=function(){g.cp(this.o);this.o=NaN;C7.Db.X.call(this)};g.Qa(D7,g.Q);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.YL,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.cA,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.oK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ka()||
(chrome.cast.addReceiverActionListener(this.A),aua(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.jC,this)),this.w=vua(this),chrome.cast.setCustomReceivers(this.w,g.Fa,(0,g.x)(function(k){this.Qb("Failed to set initial custom receivers: "+g.Nk(k))},this)),this.R("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Qb("Failed to initialize API: "+g.Nk(k));
b(!1)},this))};
g.h.WN=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.Wd(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=uua(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Fa,(0,g.x)(function(e){this.Qb("Failed to set initial custom receivers: "+g.Nk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.wt(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.XN=function(a){this.ka()?this.Qb("Setting connection data on disposed cast v2"):this.o?this.o.Ui(a):this.Qb("Setting connection data without a session")};
g.h.WO=function(){this.ka()?this.Qb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.cA,this),(0,g.x)(this.tM,this))};
g.h.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.jC,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=Yta,b=g.w("yt.mdx.remote.debug.handlers_");g.cb(b||[],a);g.je(this.o);D7.Db.X.call(this)};
g.h.Qb=function(a){i7("Controller",a)};
g.h.dA=function(a,b){this.o==a&&(b||G7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.UL=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.R("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Qb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Qb("Stopping receiver w/o session: "+a.friendlyName)}else this.Qb("onReceiverAction_ called without receiver.")};
g.h.oK=function(a){if(this.ka())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Qb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Qb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Qb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.kF,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Sq,b))};
g.h.cA=function(a){if(!this.ka()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Qb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.Wd(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.je(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.dA,this,this.o)),this.o.Ui(null));this.o.vt(a)}}};
g.h.VO=function(){return this.o?this.o.kC():null};
g.h.tM=function(a){this.ka()||(this.Qb("Failed to estabilish a session: "+g.Nk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.YL=function(a){E7("Receiver availability updated: "+a);if(!this.ka()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.R("yt-remote-cast2-availability-change",F7(this))}};
g.h.jC=function(){this.ka()||(this.w=vua(this),E7("Updating custom receivers: "+g.Nk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Fa,(0,g.x)(function(){this.Qb("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.XN;D7.prototype.setConnectedScreenStatus=D7.prototype.WN;D7.prototype.stopSession=D7.prototype.WO;D7.prototype.getCastSession=D7.prototype.VO;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];R7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Xe=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.A=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.w=a.liveIngestionTime,this.B=
!isNaN(this.w))};
R7.prototype.isAdPlaying=function(){return 1081==this.playerState};
R7.prototype.getDuration=function(){return this.B?this.G+T7(this):this.G};
R7.prototype.clone=function(){return new R7(X7(this))};g.r(Z7,g.Q);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Fa,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Fa,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Fa,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.R("remotePlayerChange")}else a8(this,g.Oa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Fa,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.R("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Qb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Qb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Oa(this.setVolume,a,b))};
g.h.dB=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Nk(b.style),g.dc(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Oa(this.dB,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Oa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Nk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.fC=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Oa(this.fC,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Oa(this.nextVideo,a,b))};
g.h.Lv=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.Lv)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.R("proxyStateChange",a,this.o)}g.Q.prototype.dispose.call(this)};
g.h.X=function(){Iua(this);this.A=null;this.B.clear();Y7(this,null);g.Q.prototype.X.call(this)};
g.h.cu=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.$a(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.RL=function(a,b){this.R(a,b)};
g.h.VJ=function(a){if(!a)this.dl(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.dl=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),Jua(this),this.R("remotePlayerChange")};
g.h.UJ=function(a){a?(Jua(this),this.R("remotePlayerChange")):this.dl(null)};
g.h.hK=function(){var a=Fua();a&&Y7(this,a)};
g.h.Qb=function(a){i7("CP",a)};g.r(f8,g.Q);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Sa.listId=c);this.Sa.videoId=d;this.Sa.index=k||0;this.Sa.state=3;U7(this.Sa,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Nk(l));this.o.connect({method:"setPlaylist",
params:g.Nk(l)},a,Wsa())}else g8("Connecting without params"),this.o.connect({},a,Wsa());Lua(this)};
g.h.dispose=function(){this.ka()||(this.R("beforeDispose"),h8(this,3));g.Q.prototype.dispose.call(this)};
g.h.X=function(){i8(this);k8(this);j8(this);g.cp(this.F);this.F=NaN;g.cp(this.G);this.G=NaN;this.w=null;g.Wq(this.O);this.O.length=0;this.o.dispose();g.Q.prototype.X.call(this);this.A=this.C=this.u=this.Sa=this.o=null};
g.h.CE=function(){this.yi(2)};
g.h.ZJ=function(){g8("Channel opened");this.J&&(this.J=!1,j8(this),this.M=g.ap((0,g.x)(function(){g8("Timing out waiting for a screen.");this.yi(1)},this),15E3));
$sa(Vta(this.o),this.T)};
g.h.WJ=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.XJ=function(a){q6();isNaN(this.gk())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.J=!0,g8("Channel error: "+a+" with reconnection in "+this.gk()+" ms"),h8(this,2))};
g.h.YJ=function(a){a.params?g8("Received: action="+a.action+", params="+g.Nk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.Ic)(a,function(c){return new d6(c)});
a=!!g.Va(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Oua(this,a);break;case "loungeScreenDisconnected":g.db(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Oua(this,!1);break;case "remoteConnected":var b=new d6(x6(a.params.device));g.Va(this.u,function(c){return b?c.id==b.id:!1})||Gsa(this.u,b);
break;case "remoteDisconnected":b=new d6(x6(a.params.device));g.db(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Qua(this,a);break;case "nowPlaying":Sua(this,a);break;case "onStateChange":Rua(this,a);break;case "onAdStateChange":Tua(this,a);break;case "onVolumeChanged":Uua(this,a);break;case "onSubtitlesTrackChanged":Pua(this,a);break;case "nowAutoplaying":Vua(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.R("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":Wua(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.KN=function(){if(this.w){var a=this.w;this.w=null;this.Sa.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.rE=function(){var a=3;this.ka()||(a=0,isNaN(this.gk())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.yi=function(a){g8("Disconnecting with "+a);i8(this);this.R("beforeDisconnect",a);1==a&&q6();Wta(this.o,a);this.dispose()};
g.h.qE=function(){var a=this.Sa;this.w&&(a=this.Sa.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.YN=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Sa.videoId&&(this.w=b.videoId,g.cp(this.F),this.F=g.ap((0,g.x)(this.KN,this),5E3));var c=[];this.Sa.listId==b.listId&&this.Sa.videoId==b.videoId&&this.Sa.index==b.index||c.push("remoteQueueChange");this.Sa.playerState==b.playerState&&this.Sa.volume==b.volume&&this.Sa.muted==b.muted&&V7(this.Sa)==V7(b)&&g.Nk(this.Sa.o)==g.Nk(b.o)||c.push("remotePlayerChange");this.Sa.reset(a);(0,g.z)(c,function(d){this.R(d)},this)};
g.h.Cw=function(){var a=this.o.C.id,b=g.Va(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.gk=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.H)():NaN};
g.h.fE=function(){return this.A||"UNSUPPORTED"};
g.h.gE=function(){return this.C||""};
g.h.OO=function(){if(!isNaN(this.gk())){var a=this.o.u;g.qn(a.o);a.start()}};
g.h.TN=function(a,b){l8(this,a,b);Nua(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.ff;f8.prototype.getProxyState=f8.prototype.rE;f8.prototype.disconnect=f8.prototype.yi;f8.prototype.getPlayerContextData=f8.prototype.qE;f8.prototype.setPlayerContextData=f8.prototype.YN;f8.prototype.getOtherConnectedRemoteId=f8.prototype.Cw;f8.prototype.getReconnectTimeout=f8.prototype.gk;f8.prototype.getAutoplayMode=f8.prototype.fE;f8.prototype.getAutoplayVideoId=f8.prototype.gE;f8.prototype.reconnect=f8.prototype.OO;
f8.prototype.sendMessage=f8.prototype.TN;g.r(m8,m7);g.h=m8.prototype;g.h.Wd=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.add=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.Uo=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.u.length;a<b;++a)this.dd.$_ubk(this.u[a]);this.u.length=0;this.dd=null;m7.prototype.X.call(this)};
g.h.SO=function(){this.R("screenChange")};
g.h.wL=function(){this.R("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.TO;v7.prototype.$_gsppc=v7.prototype.iC;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.Uo;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.Wd;v7.prototype.$_gos=v7.prototype.hC;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.ff;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.A);g.h=G8.prototype;
g.h.X=function(){g.A.prototype.X.call(this);this.A.stop();this.C.stop();this.J.stop();this.U();this.o.unsubscribe("proxyStateChange",this.Zz,this);this.o.unsubscribe("remotePlayerChange",this.jl,this);this.o.unsubscribe("remoteQueueChange",this.ro,this);this.o.unsubscribe("autoplayUpNext",this.Bz,this);this.o.unsubscribe("previousNextChange",this.Wz,this);this.o.unsubscribe("nowAutoplaying",this.Sz,this);this.o.unsubscribe("autoplayDismissed",this.Az,this);this.o=this.B=null};
g.h.zy=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==$7(this.o).playerState?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.M.Lw(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.TJ=function(a){this.J.yE(a)};
g.h.uO=function(a){this.zy("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.sB=function(){var a=this.u.getOption("captions","track");g.Yb(a)||K8(this,a)};
g.h.Lz=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.jl,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.O.start();this.o.subscribe("remotePlayerChange",this.jl,this)}};
g.h.SK=function(){g.Yb(this.F)||hva(this,this.F);this.G=!1};
g.h.Zz=function(a,b){this.C.stop();2==b&&this.pB()};
g.h.jl=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.BD(8));this.oB();break;case 1085:case 3:I8(this,new g.BD(9));break;case 1083:case 0:I8(this,new g.BD(2));this.M.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.BD(4));break;case 2:I8(this,new g.BD(4));H8(this,V7(a));
break;case -1:I8(this,new g.BD(64));break;case -1E3:I8(this,new g.BD(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.F=a,hva(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.O.isActive()||this.UB()}else gva(this)};
g.h.Wz=function(){this.u.R("mdxpreviousnextchange")};
g.h.ro=function(){J8(this)||gva(this)};
g.h.vD=function(){this.o.Lv()};
g.h.Bz=function(){};
g.h.Sz=function(a){isNaN(a)||this.u.R("mdxnowautoplaying",a)};
g.h.Az=function(){this.u.R("mdxautoplaycanceled")};
g.h.uH=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.UB=function(){if(J8(this)){var a=$7(this.o);this.w.Va(this.T);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.T=this.w.L(this.u,"onVolumeChange",this.Lz)}};
g.h.oB=function(){this.A.stop();if(!this.o.ka()){var a=$7(this.o);1==a.playerState&&I8(this,new g.BD(8));H8(this,V7(a));this.A.start()}};
g.h.pB=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.V);M8.prototype.w=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
M8.prototype.B=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(N8,g.V);N8.prototype.A=function(a){jva(this,a.state)};g.r(O8,g.vO);O8.prototype.J=function(){var a=this.u.getOption("remote","receivers");a&&1<a.length&&!this.u.getOption("remote","quickCast")?(this.C=g.tb(a,this.B,this),g.xO(this,(0,g.Ic)(a,this.B)),a=this.u.getOption("remote","currentReceiver"),this.re(this.B(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.B=function(a){return a.key};
O8.prototype.He=function(a){return"cast-selector-receiver"==a?"Cast...":this.C[a].name};
O8.prototype.Uc=function(a){g.vO.prototype.Uc.call(this,a);this.u.setOption("remote","currentReceiver",this.C[a]);this.w.ib()};g.r(P8,g.EP);g.h=P8.prototype;
g.h.create=function(){ava(g.Ox(this.player.P()));this.A.push(g.hp("yt-remote-before-disconnect",this.QJ,this));this.A.push(g.hp("yt-remote-connection-change",this.ZL,this));this.A.push(g.hp("yt-remote-receiver-availability-change",this.Xz,this));this.A.push(g.hp("yt-remote-auto-connect",this.XL,this));this.A.push(g.hp("yt-remote-receiver-resumed",this.WL,this));this.A.push(g.hp("mdx-privacy-popup-confirm",this.yN,this));this.A.push(g.hp("mdx-privacy-popup-cancel",this.xN,this));this.Xz()};
g.h.load=function(){this.player.cancelPlayback();g.EP.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=fva())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.O=a||0,this.player.R("progresssync",a,void 0));iva(this,this.F,this.F);g.$S(this.player.app,6)};
g.h.unload=function(){this.player.R("mdxautoplaycanceled");this.w=this.u;g.ke(this.B,this.o);this.o=this.B=null;g.EP.prototype.unload.call(this);g.$S(this.player.app,5);Q8(this)};
g.h.X=function(){g.ip(this.A);g.EP.prototype.X.call(this)};
g.h.Qk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.zy.apply(this.B,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.H};
g.h.tE=function(){return this.loaded?this.B.suggestion:null};
g.h.Xe=function(){return this.o?$7(this.o).Xe:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.O};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.P().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Qc():!a.isAdPlaying()&&this.player.Qc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.B?a.w+T7(a):a.w,isAtLiveHead:1>=(a.B?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.B?a.u+T7(a):a.u,seekableStart:0<a.A?a.A+T7(a):
a.A}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.XG=function(){this.o&&this.o.fC()};
g.h.QJ=function(a){1==a&&(this.T=this.o?$7(this.o):null)};
g.h.ZL=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.T=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.je(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.T)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.R("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Xz=function(){this.M=[this.u].concat(cva());var a=y8()||this.u;R8(this,a);this.player.la("onMdxReceiversChange")};
g.h.pN=function(a){!this.J&&g.PD(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.XL=function(){var a=y8();R8(this,a)};
g.h.WL=function(){this.w=y8()};
g.h.yN=function(){this.J=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.xN=function(){this.J=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Fc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.M;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.M.length&&"cast-selector-receiver"==this.M[1].key?(b&&P7(),!0):!1}};
g.h.YG=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.qf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.TP.remote=P8;})(_yt_player);
